name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    
    - name: Clone the repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install build

    - name: Build distribution
      run: python -m build
    
    - name: Publish the package
      uses: pypa/gh-action-pypi-publish@v1.12.4
